name: Deploy Raqamli Sovchi Landing

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}

      - name: Deploy to Server via SSH rsync
        uses: AEnterprise/rsync-deploy@v1.0.2
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-avzr --delete"
          SERVER_PORT: "22"
          FOLDER: "dist/"
          SERVER_IP: ${{ secrets.HOST }}
          USERNAME: "magnus"
          SERVER_DESTINATION: "/var/www/frontend/raqamli-sovchi-landing/dist/"
